server:
  port: 7777
  context-path: /jiujiucheck
    #热部署
  jsp-servlet:
    init-parameters:
      development: true
#数据源类型 以及参数
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    url: jdbc:mysql://123.56.44.138:3306/jiujiucheck
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
#mybatis相关配置  别名  mapper位置
mybatis:
  type-aliases-package: cn.jiujiu.entity,cn.jiujiu.DTO
  mapper-locations: classpath:cn/jiujiu/mapper/*Mapper.xml
  #让日志打印出sql语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
